# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.models.feed import Feed

class TestFeed(unittest.TestCase):
    """Feed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Feed:
        """Test Feed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Feed`
        """
        model = Feed()
        if include_optional:
            return Feed(
                id = 'feed_abc123xyz',
                name = 'SaaS Competitors',
                is_public = True,
                is_suspended = True,
                suspension_reason = 'insufficient_credits',
                rss_url = 'https://nubela.co/api/v1/feeds/feed_abc123xyz/rss.xml?token=sec_live_...',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                targets = [
                    ninjapear.models.target.Target(
                        id = 'target_abc123xyz', 
                        website_url = 'https://stripe.com', 
                        settings = ninjapear.models.target_settings.TargetSettings(
                            monitor_blog = True, 
                            monitor_x = True, 
                            monitor_website = True, 
                            frequency_days = 1, ), 
                        last_polled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_baseline_complete = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return Feed(
        )
        """

    def testFeed(self):
        """Test Feed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
