# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.api.employee_api_api import EmployeeAPIApi


class TestEmployeeAPIApi(unittest.TestCase):
    """EmployeeAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeeAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_person_profile(self) -> None:
        """Test case for get_person_profile

        Person Profile Enrichment
        """
        pass


if __name__ == '__main__':
    unittest.main()
