# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.models.customer_company import CustomerCompany

class TestCustomerCompany(unittest.TestCase):
    """CustomerCompany unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerCompany:
        """Test CustomerCompany
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerCompany`
        """
        model = CustomerCompany()
        if include_optional:
            return CustomerCompany(
                name = 'Apple',
                description = 'Apple Inc. designs, manufactures, and markets smartphones...',
                tagline = 'Think different.',
                website = 'https://www.apple.com',
                company_logo_url = 'https://nubela.co/api/v1/company/logo?website=https%3A%2F%2Fwww.apple.com',
                id = 'abc123',
                industry = 45202030,
                specialties = ["Technology","Consumer Electronics"],
                x_profile = 'https://x.com/Apple'
            )
        else:
            return CustomerCompany(
        )
        """

    def testCustomerCompany(self):
        """Test CustomerCompany"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
