# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.models.person_profile_response import PersonProfileResponse

class TestPersonProfileResponse(unittest.TestCase):
    """PersonProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonProfileResponse:
        """Test PersonProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonProfileResponse`
        """
        model = PersonProfileResponse()
        if include_optional:
            return PersonProfileResponse(
                id = '',
                slug = '',
                profile_pic_url = '',
                first_name = '',
                middle_name = '',
                last_name = '',
                full_name = '',
                bio = '',
                follower_count = 56,
                following_count = 56,
                country = '',
                city = '',
                state = '',
                x_handle = '',
                x_profile_url = '',
                personal_website = '',
                work_experience = [
                    ninjapear.models.work_experience.WorkExperience(
                        role = 'Software Engineer', 
                        company_name = '', 
                        company_website = '', 
                        description = '', 
                        start_date = '2020-01', 
                        end_date = '', )
                    ],
                education = [
                    ninjapear.models.education.Education(
                        major = '', 
                        school = '', 
                        start_date = '', 
                        end_date = '', )
                    ]
            )
        else:
            return PersonProfileResponse(
        )
        """

    def testPersonProfileResponse(self):
        """Test PersonProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
