# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.models.company_details_response import CompanyDetailsResponse

class TestCompanyDetailsResponse(unittest.TestCase):
    """CompanyDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyDetailsResponse:
        """Test CompanyDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompanyDetailsResponse`
        """
        model = CompanyDetailsResponse()
        if include_optional:
            return CompanyDetailsResponse(
                websites = ["https://stripe.com","https://stripe.dev"],
                description = 'Stripe is a technology company that builds economic infrastructure for the internet.',
                industry = 45102010,
                company_type = 'PRIVATELY_HELD',
                founded_year = 2010,
                specialties = ["Payments","Financial Services","APIs"],
                name = 'Stripe',
                tagline = 'Financial infrastructure for the internet',
                logo_url = 'https://nubela.co/api/v1/company/logo?website=https://stripe.com',
                cover_pic_url = '',
                facebook_url = 'https://facebook.com/stripe',
                twitter_url = 'https://twitter.com/stripe',
                instagram_url = '',
                employee_count = 8000,
                employee_count_range_min = 7500,
                employee_count_range_max = 8500,
                addresses = [
                    ninjapear.models.address.Address(
                        address_type = 'HEADQUARTERS', 
                        line1 = '354 Oyster Point Blvd', 
                        line2 = '', 
                        city = 'South San Francisco', 
                        state = 'CA', 
                        postal_code = '94080', 
                        country_code = 'US', 
                        country = 'United States', 
                        is_primary = True, )
                    ],
                executives = [
                    ninjapear.models.executive.Executive(
                        name = 'Patrick Collison', 
                        title = 'Chief Executive Officer', 
                        role = 'CEO', )
                    ],
                public_listing = ninjapear.models.public_listing.PublicListing(
                    stock_symbol = 'AAPL', 
                    ipo_date = '1980-12-12', 
                    isin = 'US0378331005', 
                    figi = 'BBG000B9XRY4', 
                    cusip = '037833100', 
                    lei = 'HWUPKR0MPOU8FGXBT394', 
                    cik = '0000320193', 
                    sic_code = '3571', 
                    revenue_usd = 383285000000, 
                    revenue_captured_at = '2024-09-28', 
                    ebitda_usd = 134000000000, 
                    ebitda_captured_at = '2024-09-28', )
            )
        else:
            return CompanyDetailsResponse(
        )
        """

    def testCompanyDetailsResponse(self):
        """Test CompanyDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
