# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.api.meta_api_api import MetaAPIApi


class TestMetaAPIApi(unittest.TestCase):
    """MetaAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_credit_balance(self) -> None:
        """Test case for get_credit_balance

        View Credit Balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
