# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ninjapear.api.updates_api_api import UpdatesAPIApi


class TestUpdatesAPIApi(unittest.TestCase):
    """UpdatesAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpdatesAPIApi()

    def tearDown(self) -> None:
        pass

    def test_add_target(self) -> None:
        """Test case for add_target

        Add Target
        """
        pass

    def test_create_feed(self) -> None:
        """Test case for create_feed

        Create Feed
        """
        pass

    def test_delete_feed(self) -> None:
        """Test case for delete_feed

        Delete Feed
        """
        pass

    def test_delete_target(self) -> None:
        """Test case for delete_target

        Delete Target
        """
        pass

    def test_get_feed(self) -> None:
        """Test case for get_feed

        Get Feed
        """
        pass

    def test_get_rss_feed(self) -> None:
        """Test case for get_rss_feed

        Get RSS Feed
        """
        pass

    def test_list_feeds(self) -> None:
        """Test case for list_feeds

        List Feeds
        """
        pass

    def test_update_feed(self) -> None:
        """Test case for update_feed

        Update Feed
        """
        pass

    def test_update_target(self) -> None:
        """Test case for update_target

        Update Target
        """
        pass


if __name__ == '__main__':
    unittest.main()
