# coding: utf-8

# flake8: noqa

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CompanyAPIApi",
    "ContactAPIApi",
    "CustomerAPIApi",
    "MetaAPIApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Address",
    "CompanyDetailsResponse",
    "CreditBalanceResponse",
    "CustomerCompany",
    "CustomerListingResponse",
    "DisposableEmailResponse",
    "EmployeeCountResponse",
    "Error",
    "Executive",
    "PublicListing",
]

# import apis into sdk package
from ninjapear.api.company_api_api import CompanyAPIApi as CompanyAPIApi
from ninjapear.api.contact_api_api import ContactAPIApi as ContactAPIApi
from ninjapear.api.customer_api_api import CustomerAPIApi as CustomerAPIApi
from ninjapear.api.meta_api_api import MetaAPIApi as MetaAPIApi

# import ApiClient
from ninjapear.api_response import ApiResponse as ApiResponse
from ninjapear.api_client import ApiClient as ApiClient
from ninjapear.configuration import Configuration as Configuration
from ninjapear.exceptions import OpenApiException as OpenApiException
from ninjapear.exceptions import ApiTypeError as ApiTypeError
from ninjapear.exceptions import ApiValueError as ApiValueError
from ninjapear.exceptions import ApiKeyError as ApiKeyError
from ninjapear.exceptions import ApiAttributeError as ApiAttributeError
from ninjapear.exceptions import ApiException as ApiException

# import models into sdk package
from ninjapear.models.address import Address as Address
from ninjapear.models.company_details_response import CompanyDetailsResponse as CompanyDetailsResponse
from ninjapear.models.credit_balance_response import CreditBalanceResponse as CreditBalanceResponse
from ninjapear.models.customer_company import CustomerCompany as CustomerCompany
from ninjapear.models.customer_listing_response import CustomerListingResponse as CustomerListingResponse
from ninjapear.models.disposable_email_response import DisposableEmailResponse as DisposableEmailResponse
from ninjapear.models.employee_count_response import EmployeeCountResponse as EmployeeCountResponse
from ninjapear.models.error import Error as Error
from ninjapear.models.executive import Executive as Executive
from ninjapear.models.public_listing import PublicListing as PublicListing

