# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ninjapear.models.company_update import CompanyUpdate
from typing import Optional, Set
from typing_extensions import Self

class CompanyUpdatesResponse(BaseModel):
    """
    CompanyUpdatesResponse
    """ # noqa: E501
    blogs: Optional[List[StrictStr]] = Field(default=None, description="List of blog/RSS source URLs discovered for the company")
    x_profile: Optional[StrictStr] = Field(default=None, description="X/Twitter profile URL for the company")
    updates: Optional[List[CompanyUpdate]] = Field(default=None, description="List of recent updates sorted by date descending")
    timestamp: Optional[StrictStr] = Field(default=None, description="Timestamp of the API response (ISO 8601 format)")
    __properties: ClassVar[List[str]] = ["blogs", "x_profile", "updates", "timestamp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyUpdatesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in updates (list)
        _items = []
        if self.updates:
            for _item_updates in self.updates:
                if _item_updates:
                    _items.append(_item_updates.to_dict())
            _dict['updates'] = _items
        # set to None if blogs (nullable) is None
        # and model_fields_set contains the field
        if self.blogs is None and "blogs" in self.model_fields_set:
            _dict['blogs'] = None

        # set to None if x_profile (nullable) is None
        # and model_fields_set contains the field
        if self.x_profile is None and "x_profile" in self.model_fields_set:
            _dict['x_profile'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyUpdatesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blogs": obj.get("blogs"),
            "x_profile": obj.get("x_profile"),
            "updates": [CompanyUpdate.from_dict(_item) for _item in obj["updates"]] if obj.get("updates") is not None else None,
            "timestamp": obj.get("timestamp")
        })
        return _obj


