# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CustomerCompany(BaseModel):
    """
    CustomerCompany
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Company name")
    description: Optional[StrictStr] = Field(default=None, description="A brief description of the company")
    tagline: Optional[StrictStr] = Field(default=None, description="Company tagline or slogan")
    website: Optional[StrictStr] = Field(default=None, description="Company website URL")
    company_logo_url: Optional[StrictStr] = Field(default=None, description="URL to the Company Logo API for this company")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier")
    industry: Optional[StrictInt] = Field(default=None, description="GICS 8-digit industry code")
    specialties: Optional[List[StrictStr]] = Field(default=None, description="List of company specialties")
    x_profile: Optional[StrictStr] = Field(default=None, description="X (Twitter) profile URL")
    __properties: ClassVar[List[str]] = ["name", "description", "tagline", "website", "company_logo_url", "id", "industry", "specialties", "x_profile"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerCompany from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if tagline (nullable) is None
        # and model_fields_set contains the field
        if self.tagline is None and "tagline" in self.model_fields_set:
            _dict['tagline'] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict['website'] = None

        # set to None if company_logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.company_logo_url is None and "company_logo_url" in self.model_fields_set:
            _dict['company_logo_url'] = None

        # set to None if industry (nullable) is None
        # and model_fields_set contains the field
        if self.industry is None and "industry" in self.model_fields_set:
            _dict['industry'] = None

        # set to None if specialties (nullable) is None
        # and model_fields_set contains the field
        if self.specialties is None and "specialties" in self.model_fields_set:
            _dict['specialties'] = None

        # set to None if x_profile (nullable) is None
        # and model_fields_set contains the field
        if self.x_profile is None and "x_profile" in self.model_fields_set:
            _dict['x_profile'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerCompany from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "tagline": obj.get("tagline"),
            "website": obj.get("website"),
            "company_logo_url": obj.get("company_logo_url"),
            "id": obj.get("id"),
            "industry": obj.get("industry"),
            "specialties": obj.get("specialties"),
            "x_profile": obj.get("x_profile")
        })
        return _obj


