# coding: utf-8

"""
    NinjaPear API

    NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).

    The version of the OpenAPI document: 1.0.0
    Contact: hello@nubela.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FeedSummary(BaseModel):
    """
    Feed summary returned in list endpoints (without individual targets).
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique feed identifier")
    name: Optional[StrictStr] = Field(default=None, description="Feed display name")
    is_public: Optional[StrictBool] = Field(default=None, description="Whether the RSS feed is publicly accessible without a token")
    is_suspended: Optional[StrictBool] = Field(default=None, description="Whether the feed is currently suspended")
    suspension_reason: Optional[StrictStr] = Field(default=None, description="Reason for suspension, if suspended")
    rss_url: Optional[StrictStr] = Field(default=None, description="URL to the RSS feed")
    created_at: Optional[datetime] = Field(default=None, description="When the feed was created")
    target_count: Optional[StrictInt] = Field(default=None, description="Number of active targets in this feed")
    __properties: ClassVar[List[str]] = ["id", "name", "is_public", "is_suspended", "suspension_reason", "rss_url", "created_at", "target_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeedSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if suspension_reason (nullable) is None
        # and model_fields_set contains the field
        if self.suspension_reason is None and "suspension_reason" in self.model_fields_set:
            _dict['suspension_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeedSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "is_public": obj.get("is_public"),
            "is_suspended": obj.get("is_suspended"),
            "suspension_reason": obj.get("suspension_reason"),
            "rss_url": obj.get("rss_url"),
            "created_at": obj.get("created_at"),
            "target_count": obj.get("target_count")
        })
        return _obj


